---
ID: "7d8942bb-2cc2-4477-ae1b-3fe492ee1f08"
Parent: "1995806f-0a84-42b5-93b0-88f0e2ff872c"
Template: "840d4a46-5503-49ec-bf9d-bd090946c63d"
Path: /sitecore/layout/Renderings/Project/Training
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250704T013437Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bruce.davisgoff@engagesq.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bruce.davisgoff@engagesq.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "02d232b5-e5b4-49ec-ad28-22c6451b2b27"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bruce.davisgoff@engagesq.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250704T013437Z
